name: ssh
on: 
  workflow_dispatch:
    inputs:
    tokenku:
      description: 'Input ngrok token'
      required: true
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: download ngrok
      run : |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip > /dev/null 2>&1
        unzip ngrok-stable-linux-amd64.zip > /dev/null 2>&1
        ./ngrok authtoken ${{ github.event.inputs.tokenku }}
        nohup ./ngrok tcp 3389 &>/dev/null &
        echo Downloading File
        sudo apt update && apt upgrade -y
        sudo apt install firefox -y
        sudo apt-get install -y xrdp
        sudo apt-get install mate-core mate-desktop-environment mate-notification-daemon -y
        sudo sed -i.bak '/fi/a #xrdp multiple users configuration \n mate-session \n' /etc/xrdp/startwm.sh
        sudo service xrdp start
    - name: Done! You can see the machine in list now.
      run: bash loop.sh
        
