name: ubuntu
on: 
  workflow_dispatch:
      inputs:
        tokenku:
          description: 'Input ngrok token'
          required: true
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: download ngrok
      run : |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip > /dev/null 2>&1
        unzip ngrok-stable-linux-amd64.zip > /dev/null 2>&1
        ./ngrok authtoken ${{ github.event.inputs.tokenku }}
        ./ngrok tcp --region ap 3389
        echo XRDP Address:
        curl --silent --show-error http://127.0.0.1:4040/api/tunnels | sed -nE 's/.*public_url":"tcp:..([^"]*).*/\1/p'

    - name: Done! You can see the machine in list now.
      run: bash ./loop.sh
        
